[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[program:php-fpm]
command=/usr/local/sbin/php-fpm --nodaemonize --fpm-config /usr/local/etc/php-fpm.conf
directory=/var/www/html
autostart=true
autorestart=true
startretries=3
priority=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopwaitsecs=10

[program:nginx]
command=/usr/sbin/nginx -c /tmp/nginx.conf -g "daemon off;"
directory=/var/www/html
autostart=true
autorestart=true
startretries=3
priority=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopwaitsecs=10

[program:queue]
command=/usr/local/bin/php /var/www/html/artisan queue:work --sleep=3 --tries=3 --max-time=3600 --memory=96 --timeout=90 --no-interaction
directory=/var/www/html
autostart=true
autorestart=true
startretries=3
priority=30
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopwaitsecs=60
stopsignal=TERM

[program:scheduler]
command=/usr/local/bin/php /var/www/html/artisan schedule:work --no-interaction
directory=/var/www/html
autostart=true
autorestart=true
startretries=3
priority=30
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopwaitsecs=10
stopsignal=TERM
