<?php

declare(strict_types=1);

namespace App\Models;

use App\Enums\RepeatPolicy;
use Database\Factories\GradingSchemeFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * One version of the institution's grading rules.
 *
 * active_flag is generated by MySQL. It is not fillable. A new version is a
 * new row. Unpublished results move to that row in a service later.
 */
#[Fillable([
    'name',
    'pass_mark',
    'version',
    'is_active',
    'repeat_policy',
    'resit_points_cap',
])]
class GradingScheme extends Model
{
    /** @use HasFactory<GradingSchemeFactory> */
    use HasFactory;

    /**
     * Cast the pass mark, the active flag the application writes, and the repeat policy.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'pass_mark' => 'decimal:2',
            'is_active' => 'boolean',
            'repeat_policy' => RepeatPolicy::class,
            'resit_points_cap' => 'decimal:2',
        ];
    }

    /**
     * Score components for this scheme version.
     *
     * @return HasMany<AssessmentComponent, $this>
     */
    public function assessmentComponents(): HasMany
    {
        return $this->hasMany(AssessmentComponent::class, 'scheme_id');
    }

    /**
     * Letter bands for this scheme version.
     *
     * @return HasMany<GradeBand, $this>
     */
    public function gradeBands(): HasMany
    {
        return $this->hasMany(GradeBand::class, 'scheme_id');
    }

    /**
     * Degree classes for this scheme version.
     *
     * @return HasMany<ClassificationBand, $this>
     */
    public function classificationBands(): HasMany
    {
        return $this->hasMany(ClassificationBand::class, 'scheme_id');
    }

    /**
     * Results calculated with this scheme version.
     *
     * @return HasMany<Result, $this>
     */
    public function results(): HasMany
    {
        return $this->hasMany(Result::class);
    }
}
