<?php

declare(strict_types=1);

namespace App\Models;

use App\Enums\Role;
use Database\Factories\RoleAssignmentFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * A role granted to one user, optionally scoped by faculty or department.
 *
 * faculty_scope and department_scope are generated by MySQL. They are not fillable.
 */
#[Fillable(['user_id', 'role', 'faculty_id', 'department_id'])]
class RoleAssignment extends Model
{
    /** @use HasFactory<RoleAssignmentFactory> */
    use HasFactory;

    /**
     * Cast the role string to the Role enum.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'role' => Role::class,
        ];
    }

    /**
     * Account this assignment belongs to.
     *
     * @return BelongsTo<User, $this>
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
