<?php

declare(strict_types=1);

namespace App\Models;

use Database\Factories\SemesterFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * A semester inside one academic session.
 *
 * active_flag is generated by MySQL. It is not fillable.
 */
#[Fillable(['session_id', 'name', 'is_active', 'registration_deadline', 'add_drop_deadline'])]
class Semester extends Model
{
    /** @use HasFactory<SemesterFactory> */
    use HasFactory;

    /**
     * Cast the active flag and the deadline instants.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'is_active' => 'boolean',
            'registration_deadline' => 'datetime',
            'add_drop_deadline' => 'datetime',
        ];
    }

    /**
     * Academic session this semester belongs to.
     *
     * @return BelongsTo<AcademicSession, $this>
     */
    public function academicSession(): BelongsTo
    {
        return $this->belongsTo(AcademicSession::class, 'session_id');
    }
}
