<?php

declare(strict_types=1);

namespace App\Models;

use Database\Factories\SemesterFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * A semester inside one academic session.
 *
 * active_flag is generated by MySQL. It is not fillable.
 */
#[Fillable(['session_id', 'name', 'is_active', 'registration_deadline', 'add_drop_deadline'])]
class Semester extends Model
{
    /** @use HasFactory<SemesterFactory> */
    use HasFactory;

    /**
     * Cast the active flag and the deadline instants.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'is_active' => 'boolean',
            'registration_deadline' => 'datetime',
            'add_drop_deadline' => 'datetime',
        ];
    }

    /**
     * Limit the query to the active semester.
     *
     * At most one row has is_active set. The flag column enforces that.
     *
     * @param  Builder<static>  $query
     * @return Builder<static>
     */
    public function scopeActive(Builder $query): Builder
    {
        return $query->where('is_active', true);
    }

    /**
     * Academic session this semester belongs to.
     *
     * @return BelongsTo<AcademicSession, $this>
     */
    public function academicSession(): BelongsTo
    {
        return $this->belongsTo(AcademicSession::class, 'session_id');
    }

    /**
     * Course registrations for this semester.
     *
     * @return HasMany<CourseRegistration, $this>
     */
    public function courseRegistrations(): HasMany
    {
        return $this->hasMany(CourseRegistration::class);
    }

    /**
     * Class meetings in this semester.
     *
     * @return HasMany<AttendanceSession, $this>
     */
    public function attendanceSessions(): HasMany
    {
        return $this->hasMany(AttendanceSession::class);
    }

    /**
     * Exam sittings in this semester.
     *
     * @return HasMany<ExamTimetable, $this>
     */
    public function examTimetable(): HasMany
    {
        return $this->hasMany(ExamTimetable::class);
    }

    /**
     * Staff teaching assignments in this semester.
     *
     * @return HasMany<CourseAssignment, $this>
     */
    public function courseAssignments(): HasMany
    {
        return $this->hasMany(CourseAssignment::class);
    }
}
